### ISSUE TITLE
Setting up with Docker docs is not working

### ISSUE THREAD

**Issue by moficodes** [Nexmo/nexmo-developer#3778]
## Description

Following the instruction to run locally.

```bash
docker-compose up

docker-compose run web bundle exec rake db:migrate
```

Visiting localhost:3000 gives error `"We're sorry, but something went wrong."`. As suggested running 

```bash
docker-compose run web bundle exec rake db:migrate
```

## What did you expect to happen?

The docs website loads.

## What actually happened?

Get the error page.

## Steps to reproduce:

Follow the docker instruction.

**Comment by moficodes** [comment]
Using docker on Mac.

**Comment by pardel** [comment]
@moficodes are there any Rails logs we can use to diagnose the problem?

**Comment by moficodes** [comment]
```
web_1  | I, [2021-08-20T13:13:57.095869 #1]  INFO -- : [03f67347-9372-405a-9594-9e7e233adeb1] Started GET "/" for 172.21.0.1 at 2021-08-20 13:13:57 +0000
web_1  | I, [2021-08-20T13:13:57.112614 #1]  INFO -- : [03f67347-9372-405a-9594-9e7e233adeb1] Processing by StaticController#landing as HTML
web_1  | D, [2021-08-20T13:13:57.126504 #1] DEBUG -- : [03f67347-9372-405a-9594-9e7e233adeb1]   Rendering layout layouts/landing.html.erb
web_1  | D, [2021-08-20T13:13:57.126823 #1] DEBUG -- : [03f67347-9372-405a-9594-9e7e233adeb1]   Rendering /docs/custom/views/static/landing.html.erb within layouts/landing
web_1  | D, [2021-08-20T13:13:57.155118 #1] DEBUG -- : [03f67347-9372-405a-9594-9e7e233adeb1]   Rendered layouts/partials/_code_snippets_home.html.erb (Duration: 21.4ms | Allocations: 4897)
web_1  | I, [2021-08-20T13:13:57.155898 #1]  INFO -- : [03f67347-9372-405a-9594-9e7e233adeb1]   Rendered /docs/custom/views/static/landing.html.erb within layouts/landing (Duration: 28.8ms | Allocations: 6329)
web_1  | I, [2021-08-20T13:13:57.156394 #1]  INFO -- : [03f67347-9372-405a-9594-9e7e233adeb1]   Rendered layout layouts/landing.html.erb (Duration: 29.7ms | Allocations: 6436)
web_1  | I, [2021-08-20T13:13:57.157418 #1]  INFO -- : [03f67347-9372-405a-9594-9e7e233adeb1] Completed 500 Internal Server Error in 44ms (Allocations: 8049)
web_1  | D, [2021-08-20T13:13:57.158992 #1] DEBUG -- [Bugsnag]: [03f67347-9372-405a-9594-9e7e233adeb1] Not notifying due to an invalid api_key
web_1  | F, [2021-08-20T13:13:57.160935 #1] FATAL -- : [03f67347-9372-405a-9594-9e7e233adeb1]
web_1  | [03f67347-9372-405a-9594-9e7e233adeb1] ActionView::Template::Error (CodeSnippetFilter - Could not load /docs/.repos/vonage/vonage-dotnet-code-snippets/DotNetCliCodeSnippets/Messaging/SendSms.cs for language dotnet):
web_1  | [03f67347-9372-405a-9594-9e7e233adeb1]     23:   <div class="glide__track" data-glide-el="track">
web_1  | [03f67347-9372-405a-9594-9e7e233adeb1]     24:     <% cache presenter.cache_key do %>
web_1  | [03f67347-9372-405a-9594-9e7e233adeb1]     25:       <div class="glide__slides">
web_1  | [03f67347-9372-405a-9594-9e7e233adeb1]     26:         <% presenter.code_snippets.each do |snippet| %>
web_1  | [03f67347-9372-405a-9594-9e7e233adeb1]     27:           <div class="glide__slide" data-glide-autoplay="4000">
web_1  | [03f67347-9372-405a-9594-9e7e233adeb1]     28:             <p class="Adp-code-snippet__title"><b><%= snippet.title %></b></p>
web_1  | [03f67347-9372-405a-9594-9e7e233adeb1]     29:             <div class="Adp-code-snippet">
web_1  | [03f67347-9372-405a-9594-9e7e233adeb1]
web_1  | [03f67347-9372-405a-9594-9e7e233adeb1] (erb):8:in `render'
web_1  | [03f67347-9372-405a-9594-9e7e233adeb1] app/presenters/code_snippets_home_presenter.rb:5:in `block in code_snippets'
web_1  | [03f67347-9372-405a-9594-9e7e233adeb1] app/presenters/code_snippets_home_presenter.rb:3:in `map'
web_1  | [03f67347-9372-405a-9594-9e7e233adeb1] app/presenters/code_snippets_home_presenter.rb:3:in `code_snippets'
web_1  | [03f67347-9372-405a-9594-9e7e233adeb1] app/views/layouts/partials/_code_snippets_home.html.erb:26
web_1  | [03f67347-9372-405a-9594-9e7e233adeb1] app/views/layouts/partials/_code_snippets_home.html.erb:24
web_1  | [03f67347-9372-405a-9594-9e7e233adeb1] app/controllers/static_controller.rb:71:in `landing'
web_1  | [03f67347-9372-405a-9594-9e7e233adeb1] app/middleware/nexmo_developer/visitor_id.rb:10:in `call'
web_1  | [03f67347-9372-405a-9594-9e7e233adeb1] app/middleware/nexmo_developer/building_block_redirect.rb:15:in `call'
```

**Comment by moficodes** [comment]
Found the issue. 

Needed to initialize submodule since `docker-compose` mounts everything at `/docs` 

We need to add that step in the docker instruction. or move it up to general instruction. Right now its only in local setup with ruby.
